//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camuda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public long id { get; set; }
        public string dev { get; set; }
        public string dri { get; set; }
        public string tim { get; set; }
        public string dat { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public string wng { get; set; }
        public Nullable<double> anl { get; set; }
        public Nullable<double> pul { get; set; }
        public string opt { get; set; }
        public string dig { get; set; }
        public Nullable<double> vgp { get; set; }
        public Nullable<double> dir { get; set; }
        public Nullable<double> vsr { get; set; }
        public Nullable<double> mil { get; set; }
        public Nullable<int> old { get; set; }
        public Nullable<int> sat { get; set; }
        public Nullable<double> hwv { get; set; }
        public Nullable<double> fwv { get; set; }
        public Nullable<double> clt { get; set; }
        public Nullable<double> clg { get; set; }
        public Nullable<int> sig { get; set; }
        public Nullable<double> hdo { get; set; }
        public Nullable<int> bat { get; set; }
        public Nullable<double> epw { get; set; }
        public string drt { get; set; }
        public string cdt { get; set; }
        public Nullable<int> date_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
